# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f750e9102aa6e66aac7821931e45e2ec"
name = "T1Pagos"
handle = "t1pagos-1"
application_url = "https://activated-based-merit-visible.trycloudflare.com"
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "t1pagos.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_payment_gateways,write_payment_sessions"

[auth]
redirect_urls = [
  "https://activated-based-merit-visible.trycloudflare.com/auth/callback",
  "https://activated-based-merit-visible.trycloudflare.com/auth/shopify/callback",
  "https://activated-based-merit-visible.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
